- config.sample.js
- controllers/uploadController.js
- package.json
Closes https://github.com/WeebDev/loli-safe/issues/10
Also fixes some pre-existing issues with thumbnail generation
> support thumbnails for .webm and .mp4 files

- README.md
> link change

- config.sample.js
- controllers/uploadController.js
Added an option to add file extensions to the config which will be rejected.
Already added few file extensions which should be blocked to the config.
(https://github.com/WeebDev/loli-safe/issues/19)
> added array with blocked file extensions

- config.sample.js
> Updated blocked extensions.

- lolisafe.js
- package.json
> Implemented Helmet

- pages/home.html
- public/css/style.css
- public/js/home.js
Users are now able to upload to an album over the website. I'm not sure if the styling of the select box is okay with you but I found it pretty fitting.
> Added upload to album through website

- pages/home.html
> Proper casing of GitHub

- controllers/uploadController.js
Tested working with a couple file types. Fixed some coding errors from earlier revision.
> Delete thumbnails when file deletes

- pages/home.html
- public/js/home.js
This has been tested with Chrome 61.0.3163.100 locally, haven't tested this on a web server.
> Make ShareX link download a sharex file if you're logged in

- README.md
> added updx.xyz

- .gitignore
- README.md
- controllers/uploadController.js
> Added safe.fiery.me to README.md.

- README.md
> Added kayo.pics

- controllers/uploadController.js
- public/js/dashboard.js
- public/js/home.js
I wonder why I can't see the diffs from vscode 🤔
this may not be 100% compatible with https://github.com/WeebDev/lolisafe/pull/93
edit: ok, im tired
> no-mixed-spaces-and-tabs

- controllers/albumsController.js
- controllers/authController.js
- controllers/utilsController.js
- database/db.js
- public/js/auth.js
- public/js/dashboard.js
- public/js/home.js
i ran all js files through eslint and auto-fixed semicolons only
tbh semicolons are overrated
> SEMICOLONS, ermahgerd

- pages/album.html
- pages/auth.html
- pages/dashboard.html
- pages/faq.html
- pages/home.html
> Fixed more urls

- README.md
> Added site

- public/css/style.css
Fixed an issue cutting off delete button in dashboard
> Fixed an issue with dashboard

- README.md
I site I made 3 months ago, I think it's okay now for it to be here.
> Add new site

- README.md
When you can't type properly and do 2 commits.
> Added My Site

- README.md
- UPDX - uses SSL, so no need to keep http: link.
- Kayo.pics - redirects to kayo.moe
- safe.waliant.pw - entire waliant.pw is down right now.
- a.hyper.lol - added a space because I don't like when words are unnecessarily mashed together.
> Site list revision

- config.sample.js
> Added .exec to blacklist

- controllers/utilsController.js
> fix missing sharp import

- README.md
For more information, see my comment on #149
> bad service

- src/site/pages/dashboard/account.vue
As discussed before, an adjustment for the wording alongside a grammatical fix.
In PR form as suggested by you.
> Adjust wording & fix grammar in account settings

- src/api/routes/albums/albumEditPOST.js
- src/api/structures/Route.js
- src/site/components/album/AlbumDetails.vue
- src/site/components/album/AlbumEntry.vue
- src/site/store/albums.js
fix: nsfw album toggle doesn't propagate the state change properly
fix: add nsfw flag to the booleanFields in knex postProcessResponse
> fix: nsfw album toggle doesn't propagate the state change properly

- src/api/routes/albums/albumPOST.js
- src/api/routes/albums/albumsGET.js
- src/api/routes/albums/link/linkPOST.js
- src/api/routes/files/albumAddPOST.js
Allows Api Key to do the following:
- Get albums for the user
- Create albums
- Create Album links
- Add uploaded files to an album
> Alow API Access to additional endpoints

- docs/sites.md
safe.fiery.moe is no longer active. see: https://blog.fiery.me/safe-fiery-me-shutting-down-soon-tm
> Remove safe.fiery.moe from sites.md

- backend/src/main.ts
- backend/src/routes/files/AddFileToAlbum.ts
- backend/src/routes/files/Upload.ts
- backend/src/utils/File.ts
Via `albumUuid` header
Also updated `AddFileToAlbum.ts` to use the same shared function from `File` util (it comes with timestamp updater apparently)
> feature/hyper-express <- upload to album

- backend/src/routes/admin/users/GetUserWithFiles.ts
- backend/src/routes/album/GetAlbum.ts
- frontend/src/components/modals/FileInformationModal.vue
- frontend/src/components/pagination/Pagination.vue
- frontend/src/components/table/FilesTable.vue
- frontend/src/components/upload/Upload.vue
- frontend/src/components/wrappers/FilesWrapper.vue
- frontend/src/main.ts
- frontend/src/pages/dashboard/admin/files.vue
- frontend/src/pages/dashboard/admin/user/[uuid].vue
- frontend/src/pages/dashboard/albums/[uuid].vue
- frontend/src/pages/dashboard/uploads.vue
- frontend/src/store/albums.ts
- frontend/src/store/files.ts
- frontend/src/use/api.ts
- frontend/src/use/file.ts
- frontend/src/use/log.ts
* Added ability to paste clipboard file to upload.
* Added url query parameter for current page.
* Added dropdown to the pagination.
* Disable previous/next buttons on the pagination component when needed.
> Improvements

- .github/workflows/docker-image.yml
- Dockerfile
- docker-compose.example.yml
- docs/docker/caddy/docker-compose.yml
- docs/docker/docker.md
- docs/docker/nginx/docker-compose.yml
I did 10 minutes of testing. Good luck kana. :)
> Use alpine image for smaller image size

- packages/frontend/src/components/sidebar/Sidebar.vue
- packages/frontend/src/pages/a/[identifier].vue
- packages/frontend/src/pages/dashboard/account.vue
- packages/frontend/src/pages/dashboard/admin/files.vue
- packages/frontend/src/pages/dashboard/admin/invites.vue
- packages/frontend/src/pages/dashboard/admin/settings.vue
- packages/frontend/src/pages/dashboard/admin/statistics.vue
- packages/frontend/src/pages/dashboard/admin/user/[uuid].vue
- packages/frontend/src/pages/dashboard/admin/users.vue
- packages/frontend/src/pages/dashboard/albums/[uuid].vue
- packages/frontend/src/pages/dashboard/albums/index.vue
- packages/frontend/src/pages/dashboard/uploads.vue
caused by the scrollbar fix. smh.
> fix: elements appearing offscreen

- packages/frontend/src/components/upload/ChibiUploader.vue
Smh kana.
Also fixed the border color not reverting on drop.
> [Fix] Drag and drop not working (again)

- packages/backend/src/routes/admin/users/GetUserWithFiles.ts
- packages/frontend/src/App.vue
- packages/frontend/src/components/breadcrumbs/Breadcrumbs.vue
- packages/frontend/src/components/header/Header.vue
- packages/frontend/src/components/modals/FileInformationModal.vue
- packages/frontend/src/components/pagination/Pagination.vue
- packages/frontend/src/components/sidebar/Sidebar.vue
- packages/frontend/src/components/upload/ChibiUploader.vue
- packages/frontend/src/components/wrappers/FilesWrapper.vue
- packages/frontend/src/pages/dashboard/admin/settings.vue
- packages/frontend/src/pages/index.vue
- packages/frontend/src/pages/login.vue
- packages/frontend/src/pages/register.vue
- packages/frontend/src/store/modals.ts
- packages/frontend/src/types.ts
- packages/frontend/tailwind.config.js
- Fixed admin modal not showing user info
- Added pagination to the bottom of the page too
- Made the site mobile-friendly-ish
> [Fixes] Design issues mostly

- packages/backend/src/routes/files/Search.ts
- packages/frontend/components.d.ts
- packages/frontend/package.json
- packages/frontend/src/App.vue
- packages/frontend/src/components/modals/SearchModal.vue
- packages/frontend/src/components/pagination/Pagination.vue
- packages/frontend/src/pages/dashboard/uploads.vue
- packages/frontend/src/store/files.ts
- packages/frontend/src/store/modals.ts
- packages/frontend/src/use/api.ts
- packages/frontend/tailwind.config.js
- yarn.lock
> [Feature] Add command palette

- packages/backend/src/routes/admin/files/GetFiles.ts
- packages/backend/src/routes/admin/files/PurgePublic.ts
- packages/backend/src/routes/admin/ip/PurgeFiles.ts
- packages/backend/src/routes/admin/users/Purge.ts
- packages/backend/src/utils/File.ts
- packages/frontend/src/components/forms/InputWithOverlappingLabel.vue
- packages/frontend/src/components/modals/DeleteFileModal.vue
- packages/frontend/src/components/modals/GenericConfirmationModal.vue
- packages/frontend/src/components/modals/ManageUserModal.vue
- packages/frontend/src/pages/dashboard/admin/files.vue
- packages/frontend/src/pages/dashboard/admin/ip/[ip].vue
- packages/frontend/src/store/files.ts
- packages/frontend/src/use/api.ts
- Added ability to filter uploads by anonymous or not
- Fixed an issue where purging a user wouldn't remove the actual files from storage
- Added ability to purge anonymous uploads
- Added ability to purge uploads per IP address
> [Feature] Public and IP uploads management

- packages/frontend/src/pages/dashboard/account.vue
- Improved contrast on user settings page
- Blur API Key until hovering over
> [Fix] Style for user settings

- packages/backend/src/routes/album/GetAlbumWithIdentifier.schema.ts
- packages/backend/src/routes/album/GetAlbumWithIdentifier.ts
- packages/backend/src/routes/album/links/GetAlbumLinks.schema.ts
- packages/frontend/src/App.vue
- packages/frontend/src/components/masonry/Masonry.vue
- packages/frontend/src/components/modals/AlbumSettingsModal.vue
- packages/frontend/src/components/modals/ManageAlbumModal.vue
- packages/frontend/src/components/pagination/Pagination.vue
- packages/frontend/src/components/wrappers/FilesWrapper.vue
- packages/frontend/src/pages/a/[identifier].vue
- packages/frontend/src/use/api.ts
- Added pagination to public albums
- Fixed broken video previews being too small to click
- Aligned the change password message for the admin of the instance
- Fixed album schema being wrong
- Improved pagination component
> [Fixes] Pagination, Video preview, etc

- packages/frontend/package.json
- packages/frontend/src/components/breadcrumbs/Breadcrumbs.vue
- packages/frontend/src/components/dropdown/AlbumDropdown.vue
- packages/frontend/src/components/header/Header.vue
- packages/frontend/src/components/masonry/Masonry.vue
- packages/frontend/src/components/masonry/MasonryPublic.vue
- packages/frontend/src/components/modals/AlbumSettingsModal.vue
- packages/frontend/src/components/modals/DeleteFileModal.vue
- packages/frontend/src/components/modals/GenericConfirmationModal.vue
- packages/frontend/src/components/modals/ManageAlbumModal.vue
- packages/frontend/src/components/modals/ManageUserModal.vue
- packages/frontend/src/components/modals/SearchModal.vue
- packages/frontend/src/components/pagination/Pagination.vue
- packages/frontend/src/components/sidebar/Sidebar.vue
- packages/frontend/src/components/table/FilesTable.vue
- packages/frontend/src/components/toast/Toast.vue
- packages/frontend/src/components/upload/ChibiUploader.vue
- packages/frontend/src/components/wrappers/FilesWrapper.vue
- packages/frontend/src/pages/dashboard/admin/statistics.vue
- packages/frontend/src/pages/dashboard/albums/index.vue
- packages/frontend/src/pages/index.vue
- packages/frontend/tsconfig.json
- packages/frontend/vite.config.ts
- yarn.lock
- Replaced icon pack
- Added icons to pagination
- Moved docs link in the main page
- Made the masonry image prettier by adding some hover effects
> [Design] Some updates

- packages/backend/package.json
- packages/backend/src/routes/files/Upload.ts
- packages/frontend/package.json
- yarn.lock
* Added missing return statement in the upload route.
* Bumped uploader versions due to important fixes.
> [Fix] Upload Stuff

- package.json
- packages/backend/src/routes/GetVersion.ts
- packages/backend/src/utils/Docs.ts
- packages/backend/src/utils/Util.ts
- packages/frontend/vite.config.ts
- In order to keep versions consistent, there is only 1 source of truth now
> [Feat] Move package version to main package.json

- packages/backend/src/main.ts
- packages/backend/src/prisma/migrations/20230701000011_update_check/migration.sql
- packages/backend/src/prisma/schema.prisma
- packages/backend/src/routes/admin/service/SaveSettings.ts
- packages/backend/src/routes/admin/service/Settings.ts
- packages/backend/src/routes/admin/service/UpdateCheck.schema.ts
- packages/backend/src/routes/admin/service/UpdateCheck.ts
- packages/backend/src/structures/interfaces.ts
- packages/backend/src/structures/settings.ts
- packages/backend/src/utils/UpdateCheck.ts
- packages/frontend/components.d.ts
- packages/frontend/package.json
- packages/frontend/src/components/modals/ReleaseNotesModal.vue
- packages/frontend/src/components/sidebar/Sidebar.vue
- packages/frontend/src/store/index.ts
- packages/frontend/src/store/modals.ts
- packages/frontend/src/store/updateCheck.ts
- packages/frontend/src/types.ts
- packages/frontend/src/use/api.ts
- yarn.lock
Add an update check that will check if there is a newer version of chibisafe available from github every 3 hours (idk if this would be the final schedule). This would display a small banner in the sidebar at the bottom and only be visible to admins. Option to disable the update check is also implemented in the admin settings.
> [Feat] Update check

- packages/backend/src/utils/UpdateCheck.ts
- packages/frontend/src/components/modals/ReleaseNotesModal.vue
> [Fix] Update check version comparison

- README.md
Added ports and made it identical compared to the docker-compose.yml
> Fix README.md's docker run.

- packages/frontend/src/pages/dashboard/admin/statistics.vue
Just makes the statistics more readable instead of showing the plain json response. 
This is my first time doing anything in vue, let me know if I did something stupid. :sweat_smile:
> [Feature] Format values on statistics page

- packages/backend/src/utils/Snippet.ts
- packages/frontend/src/components/modals/TextEditorModal.vue
- packages/frontend/src/pages/s/[identifier].vue
- Add copy and open buttons to the shared snippet view
- Fix the wrong port being replaced
- Debounce language detection so it doesn't lag when typing
> [Fixed] snippets

- packages/frontend/src/components/dialogs/AlbumSettingsDialog.vue
- packages/frontend/src/components/dialogs/ConfirmationDialog.vue
- packages/frontend/src/components/modals/FileInformationModal.vue
- packages/frontend/src/components/sidebar/Sidebar.vue
- packages/frontend/src/components/table/AlbumLinksTable.vue
- packages/frontend/src/components/table/FilesTable.vue
- packages/frontend/src/components/table/InvitesTable.vue
- packages/frontend/src/components/table/UsersTable.vue
- packages/frontend/src/components/ui/alert-dialog/AlertDialogTrigger.vue
- packages/frontend/src/pages/dashboard/account.vue
- packages/frontend/src/pages/dashboard/admin/files.vue
- packages/frontend/src/pages/dashboard/admin/ip/[ip].vue
- packages/frontend/src/pages/dashboard/snippets/[uuid].vue
- Fix hamburger menu not working
- Fix double button rendering on dialogs
> [Fix] UI stuff

- packages/frontend/src/components/dialogs/FileInformationDialog.vue
- packages/frontend/src/components/dialogs/TextEditorDialog.vue
- packages/frontend/src/components/masonry/Masonry.vue
- packages/frontend/src/components/table/FilesTable.vue
- packages/frontend/src/components/table/InvitesTable.vue
- packages/frontend/src/components/upload/ChibiUploader.vue
- packages/frontend/src/pages/dashboard/admin/invites.vue
- packages/frontend/src/pages/dashboard/snippets/index.vue
- packages/frontend/src/use/api.ts
- If the user is an admin, show FileInformationDialog when clicking on a quarantined file
- Show quarantine/allow buttons for admin
- Remove the invite from the invite list if an admin revokes it
- Feature: Be able to create snippets from the snippet dashboard
> [Feat] UI improvements

- packages/backend/src/routes/files/RegenerateFileThumbnail.schema.ts
- packages/backend/src/routes/files/RegenerateFileThumbnail.ts
- packages/backend/src/utils/File.ts
- packages/backend/src/utils/Thumbnails.ts
- packages/frontend/src/components/dialogs/FileInformationDialog.vue
- packages/frontend/src/pages/dashboard/admin/ip/[ip].vue
- packages/frontend/src/use/api.ts
- Feat: added a button on the File modal to regenerate broken thumbnails
- Feat: add svg files to the list of images to generate thumbnails for
> [Feature] Regenerate broken thumbnails

- packages/frontend/src/components/dialogs/FileInformationDialog.vue
- Added scroll when the screen is small or the image is weird, so the content doesn't overflow
> [Feat] Add scrollbar to file information dialog

- packages/frontend/src/components/wrappers/FilesWrapper.vue
- packages/frontend/src/pages/a/[identifier].vue
- packages/frontend/src/pages/dashboard/admin/user/[uuid].vue
- packages/frontend/src/store/albums.ts
- Fix: broken pagination on public album page
- Fix: broken pagination on the bottom pagination component
- Fix: broken pagination arrows would lead to `?page=NaN`
- Fix: not being able to view a user's files as admin
> [Fixes] Pagination and file fetching

- .gitignore
- package.json
- packages/frontend/src/components/wrappers/FilesWrapper.vue
- packages/frontend/src/pages/dashboard/albums/[uuid].vue
> [Fix] Use album uuid as query key

- package.json
- packages/frontend/src/components/dialogs/FileInformationDialog.vue
- packages/frontend/src/components/highlight/Highlight.vue
- packages/frontend/src/pages/dashboard/snippets/index.vue
- packages/frontend/src/pages/s/[identifier].vue
- Fix word wrapping and overflow on snippets (#505)
- Fix files with no preview breaking the file dialog as there was no min-height (#504)
- Fix videos escaping from the file dialog bounds
> [Fix] UI fixes for snippets and media

- packages/frontend/src/components/table/FilesTable.vue
- packages/frontend/src/components/wrappers/FilesWrapper.vue
- packages/frontend/src/use/api.ts
- Hooked the previously broken search endpoint
- Added a button to trigger search (so far it was only with CTRL + K
- Added the original filename (closes #518)
> [Feat] Add search button/hook endpoint

- package.json
- packages/backend/src/routes/admin/files/AllowFile.ts
- packages/backend/src/routes/admin/files/DeleteFile.ts
- packages/backend/src/routes/admin/files/GetFile.ts
- packages/backend/src/routes/admin/files/GetFiles.ts
- packages/backend/src/routes/admin/files/PurgePublic.ts
- packages/backend/src/routes/admin/files/QuarantineFile.ts
- packages/backend/src/routes/admin/invites/CreateInvite.ts
- packages/backend/src/routes/admin/invites/DeleteInvite.ts
- packages/backend/src/routes/admin/invites/GetInvites.ts
- packages/backend/src/routes/admin/ip/Ban.ts
- packages/backend/src/routes/admin/ip/GetBannedIPs.ts
- packages/backend/src/routes/admin/ip/GetFilesFromIP.ts
- packages/backend/src/routes/admin/ip/PurgeFiles.ts
- packages/backend/src/routes/admin/ip/Unban.ts
- packages/backend/src/routes/admin/service/SaveSettings.ts
- packages/backend/src/routes/admin/service/Settings.ts
- packages/backend/src/routes/admin/service/Stats.ts
- packages/backend/src/routes/admin/service/UpdateCheck.ts
- packages/backend/src/routes/admin/users/Demote.ts
- packages/backend/src/routes/admin/users/Disable.ts
- packages/backend/src/routes/admin/users/Enable.ts
- packages/backend/src/routes/admin/users/GetAllUsers.ts
- packages/backend/src/routes/admin/users/GetUser.ts
- packages/backend/src/routes/admin/users/GetUserWithFiles.ts
- packages/backend/src/routes/admin/users/Promote.ts
- packages/backend/src/routes/admin/users/Purge.ts
- packages/backend/src/routes/admin/users/SetQuota.ts
- Add the middleware necessary for admin routes to access them with an API key (Closes #528 )
> [Fix] Add missing middleware for API key

- packages/frontend/src/components/dialogs/InputQuotaDialog.vue
- packages/frontend/src/components/table/UsersTable.vue
- Implement quota dialog again
> [Fix] Set quota dialog

- packages/frontend/src/components/dialogs/FileInformationDialog.vue
- packages/frontend/src/components/header/Header.vue
- packages/frontend/src/components/sidebar/Sidebar.vue
- packages/frontend/src/components/ui/table/Table.vue
- packages/frontend/src/components/upload/ChibiUploader.vue
- packages/frontend/src/pages/dashboard/admin/users.vue
- packages/frontend/src/pages/dashboard/albums/index.vue
- packages/frontend/src/pages/dashboard/snippets/index.vue
- packages/frontend/src/pages/index.vue
This PR intends to fix up several inconsistencies within the site. It also supersedes #543 and adds plenty of other fixes.
The affected pages/features are as follows:
- Front page
- Uploads page
- Albums page
- Tags page
- Snippets page
- Users page
- Sidebar navigation
Other pages may have been unintentionally changed due to modifications to underlying components, largely the Table component. I have checked to make sure that nothing is too out of place, and to my eye that seems to be the case.
If additional changes are needed to optimize or fix issues, please let me know.
> [Fix] Frontend code changes and fixes

- packages/frontend/src/components/masonry/Masonry.vue
Solves https://github.com/chibisafe/chibisafe/issues/550
> [Fix] Be able to download files other than image/videos from public albums

- packages/frontend/src/components/dialogs/TextEditorDialog.vue
- packages/frontend/src/components/upload/ChibiUploader.vue
> fix: text editor not opening on click

- packages/frontend/src/components/upload/ChibiUploader.vue
- packages/frontend/src/use/file.ts
> feat: drag and drop folders

- packages/backend/src/routes/admin/files/AllowFile.ts
- packages/backend/src/routes/admin/files/QuarantineFile.ts
> fix: quarantine slash

- packages/backend/package.json
- packages/backend/src/routes/files/HighlightFile.ts
- packages/next/src/components/FileTextViewer.tsx
- packages/next/src/components/FileThumbnail.tsx
- packages/next/src/components/FilesList.tsx
- packages/next/src/components/Masonry.tsx
- packages/next/src/components/dialogs/FileInformationDialog.tsx
- packages/next/src/lib/atoms/fileInformationDialog.ts
- packages/next/src/lib/file.ts
- packages/next/src/lib/request.ts
- yarn.lock
- This includes any file type that is deemed as text and highlightable by [shiki](https://github.com/shikijs/shiki)
- Files stored in S3 buckets cannot be previewed
Still missing some styling before being able to merge this.
> feat: show preview for text files

- packages/backend/src/routes/album/GetAlbumWithIdentifier.ts
- packages/backend/src/routes/album/GetAlbumWithIdentifierCount.ts
- packages/backend/src/routes/links/CreateLink.ts
- packages/backend/src/routes/links/UpdateLinkCount.ts
- packages/backend/src/routes/snippet/CreateSnippet.ts
- packages/next/src/app/a/[identifier]/page.tsx
- packages/next/src/app/l/[identifier]/route.ts
- packages/next/src/components/tables/album-links-table/AlbumLinksTable.tsx
- packages/next/src/components/tables/links-table/LinksTable.tsx
- Fixes anonymous snippet upload being accepted even on private instances
- Fixes view count updating twice by moving it to a separate endpoint
- Fixes creating infinite loops with custom URLs by pointing them to themselves
> fix: various fixes

- packages/next/src/components/FileTextViewer.tsx
- packages/next/src/components/dialogs/FileInformationDialog.tsx
- Adds a loading indicator when switching images inside the file modal
- Adds a loading indicator when waiting for text files to be highlighted
> feat: display loading indicator for modal

- packages/backend/src/routes/album/BulkAddFilesToAlbum.ts
- packages/backend/src/routes/album/BulkGetAlbumsFromFiles.ts
- packages/backend/src/routes/album/BulkRemoveFilesFromAlbum.ts
- packages/next/src/components/FilesWrapper.tsx
- packages/next/src/components/dialogs/bulk-actions/BulkAlbumActions.tsx
This PR improves the bulk actions dialog for editing albums.
Before this it was very hard to determine what was happening under the hood when removing/adding albums, but with this improved version the changes can be seen at a glance.
> feat: better bulk album management

- packages/next/src/content/guides/running-with-docker.mdx
> Fix typo (`hhave` -> `have`)

- packages/next/src/content/guides/running-with-nginx-proxy-manager.mdx
**Please do not merge this until I have tested and approved this change!**
> docs(guides): update the run with nginx proxy manager and docker guide

- README.md
* updated broken urls in README.md to the new ones in https://github.com/chibisafe/guides
~~Is it too early for this PR? If not I will go ahead and fix the rest.~~
> docs: update docs url

- packages/next/package.json
- packages/next/src/app/compare/[file1]/[file2]/layout.tsx
- packages/next/src/app/compare/[file1]/[file2]/page.tsx
- packages/next/src/components/CompareSlider.tsx
- packages/next/src/components/FilesWrapper.tsx
- packages/next/src/components/dialogs/bulk-actions/BulkCompareAction.tsx
- yarn.lock
After clicking on compare, a new tab is opened with the slider.
https://github.com/user-attachments/assets/4bb0780d-5ef7-4e26-bf4c-355e485e9cc7
> Add a comparison slider when bulk selecting 2 images

- packages/next/src/app/(home)/page.tsx
> Fix typo in description
