README.md, nginx-ssl.sample.conf, nginx.sample.conf
- Renamed `nginx.sample.conf` to `nginx-ssl.sample.conf`
- Added `nginx.sample.conf` that only supports HTTPS
- Also matched the port in both configs to `9999` as `config.sample.js` has. 
- Updated the README to link to both configurations.
=> Added HTTP Version of NGINX sample configuration

config.sample.js
It seems that COM files can still be run in Windows, and they behave like any other executable.
PS1 files are scripts, so I put them on the list.
=> Ban of .com and .ps1 uploads

config.sample.js, controllers/uploadController.js
Looks good? I was debating on whether I should use 3 tries or 1 try for the default value, but in the end I decided to go with 1 try as to "sort of" follow the old behavior. Though technically speaking, the old behavior was to replace the old file, but in here it would return an error instead.
Also the comments in the config file could probably be phrased better but I'm having a mental block atm.
Other than that, do you mind sharing your eslint config file or something? I had to turn off 27 rules (28 including func-names in the package.json file) just so that none of the JS files show any errors/warnings. Though I can't really be sure whether it was my eslint not being setup properly or something ~~(*cough*, standard master race)~~.
=> Patch to allow "retries" when generating random name

controllers/uploadController.js, public/js/home.js
Fixed the way error when adding album is being handled.
I used "file(s)" since technically speaking you can upload more than one file at a time from the API (right?) :thinking: 
Btw, previously whenever a file could not be added to album, the error would never be shown to user, and it would throw an error in terminal about being unable to set headers and whatnots (https://github.com/WeebDev/lolisafe/issues/91).
=> fixed "add to album" error on uploads

README.md
dmca.gripe allows for censorship-free and permanent filehosting on-top of lolisafe.
=> added dmca.gripe

public/css/style.css, public/js/dashboard.js
I hate "hover-to-reveal-hidden-UI" bullshit so it just adds a button below each thumbnail. The CSS standardizes the thumbnail heights so that the delete buttons stay aligned.
Looks like this:
=> Album View File Deletion

nginx-ssl.sample.conf, nginx.sample.conf
So that non-English text isn't mangled, all `text/*` types are sent with `utf-8` encoding by adding the following:
```
map $sent_http_content_type $charset {
~^text/ utf8;
}
server {
// Other settings
charset $charset;
charset_types *;
}
```
I can't think of a good reason to send the nginx version in the headers, so, for what may as well be security theater, the following is added:
```
server_tokens off;
```
=> Small nginx.config improvements

nginx-ssl.sample.conf, nginx.sample.conf
Unknown directive `charset_type`, because the proper directive is `charset_types`.
=> Fixes typo of charset_Type

public/js/dashboard.js
If a file did not have a thumbnail the delete button would not render because I missed this `else` clause. :(
=> Fix: File Deletion for No Thumbnail in Album View

README.md
Removed:
- safe.waliant.pw (Unresponsive, DNS has expired: https://securitytrails.com/domain/safe.waliant.pw/history/a)
- vortex.64i.de (Doesn't have lolisafe instance, just shows main page)
=> Removed inactive sites

package.json
Updates dependencies for node 10.x and 11.x
Couldn't test under 7.x nor 8.x, but the npm pages of the dependencies don't mention incompatibilities with these versions. This should probably be tested.
=> updated deps to make it work with node 10.x

README.md
A few steps were removed from this section earlier but the numbering weren't updated. This PR fixes that.
=> docs(Readme): fix numbering for installation steps

docs/nginx.md
The config check run by nginx will fail because this directive is stated twice
=> Remove duplicate proxy_redirect directive

package-lock.json, package.json
In my installation, Chibisafe is crashing when generating image thumbnails. I was not able to determine exactly why because Node simply crashed with an `ELIFECYCLE` and no other helful logs. Through troubleshooting I narrowed it down to the call to `sharp` when generating a square thumbnail in `ThumbUtil.generateThumbnailForImage`.
After upgrading the sharp package to 0.29.x (0.29.3 currently), the problem was resolved.
=> Update sharp package to fix crash

backend/package-lock.json, backend/package.json, backend/src/main.ts, backend/src/routes/files/Upload.ts, backend/src/structures/interfaces.ts
This also updates Hyper-Express to latest (6.4.10) as I discovered a "workaround"
I don't even know why a workaround is necessary, but alas
Gist of the change is what I described in Discord, which is, incoming upload streams will always be stored to disk first
Validations are deferred until all the multipart field(s) have been processed
I experimented with "consuming the streams into the void", or something of that nature, but I failed to make any breakthroughs
So had to settle with actually storing to disk
In practice, files that previously would have been accepted just fine, should still behave the same
=> feature/hyper-express <- upload v2

README.md
Python 2.7 is required by node-gyp during package installation.
- npm version `9.1.3`
- node veresion `18.12.1`
=> Update README.md to include python2.7 in pre-requisites

packages/backend/src/main.ts, packages/backend/src/prisma/migrations/20230629002506_add_path_and_mixed_case_settings/migration.sql, packages/backend/src/prisma/schema.prisma, packages/backend/src/routes/admin/files/GetFile.ts, packages/backend/src/routes/admin/files/GetFiles.ts, packages/backend/src/routes/admin/ip/GetFilesFromIP.ts, packages/backend/src/routes/admin/users/GetUser.ts, packages/backend/src/routes/admin/users/GetUserWithFiles.ts, packages/backend/src/routes/album/GetAlbum.ts, packages/backend/src/routes/album/GetAlbumWithIdentifier.ts, packages/backend/src/routes/album/GetAlbums.ts, packages/backend/src/routes/auth/Login.ts, packages/backend/src/routes/auth/Register.ts, packages/backend/src/routes/files/GetFile.ts, packages/backend/src/routes/files/GetFiles.ts, packages/backend/src/routes/files/Search.ts, packages/backend/src/routes/files/Upload.ts, packages/backend/src/structures/interfaces.ts, packages/backend/src/structures/settings.ts, packages/backend/src/utils/File.ts, packages/frontend/src/App.vue
This PR does:
- Adds the possibility of defining a custom domain to serve files from
- Adds the possibility of having mixed case letters in the generated filenames
- For reference, with only 4 digits you could have 1,679,616 combinations. With mixed case, you could have 14,776,336 combinations
- On Windows this is turned off by default and can't be changed
=> [Feature] Add custom domain and mixed case filenames

packages/backend/src/routes/admin/files/GetFiles.ts, packages/backend/src/structures/schemas/FilesAsAdmin.ts
Due to the recent addition of route schemas, the `publicOnly` query option was no longer working.
=> [Fix] Not able to fetch only anonymous files.

packages/backend/package.json, packages/backend/src/main.ts, packages/backend/src/structures/settings.ts, packages/backend/src/utils/Snippet.ts, packages/frontend/src/components/highlight/Highlight.vue
- Enable loading .env vars on production start
- Enable `/s/` for snippets during production
- Rewrite the host when running in development mode so that the snippet can be opened from the frontend
- Prevent line numbers to be selected
=> [Feature] Load .env for production, fixed

packages/backend/src/main.ts, packages/backend/src/routes/album/GetAlbumWithIdentifier.ts, packages/frontend/src/components/masonry/Masonry.vue, packages/frontend/src/components/sidebar/Sidebar.vue, packages/frontend/src/pages/a/[identifier].vue
- Public albums were not being displayed correctly
- Public albums were not scrollable
- Public album files were not clickable
- Public albums endpoint would hang with 500 API error when updating the amount of visits a link has, which has now been commented out for the time being
- New version notification wasn't properly aligned
- Dashboard now shows chibisafe version at the bottom
=> [Fix] Public albums and update notification

packages/migration/src/index.ts, packages/migration/tsconfig.json
this makes the script properly executable, and properly migrates the v4 database to the v5 schema.
=> fix: migrate-v4-from-v5 script

packages/backend/src/routes/admin/files/DeleteFile.ts, packages/backend/src/routes/admin/users/GetUserWithFiles.ts, packages/frontend/src/components/dialogs/FileInformationDialog.vue
- Fixed an issue where an admin wouldn't be able to delete a quarantined item (fixes #508)
- Fixed an issue where deleting a quarantined item wouldn't get rid of the file, only the database entry
=> [Fix] Properly delete quarantined items

packages/backend/src/routes/auth/Login.ts, packages/frontend/src/components/dialogs/FileInformationDialog.vue, packages/frontend/src/use/file.ts
I've undertaken two slight changes which I myself have now on my instance. First, I've changed the "file.ts" file to now count 1k bytes as one kilo and not 1024. This issue I've detailed in #521. 
The second edit is something that I've recently noticed and found worth changing. It is to remove the "user doesn't exist" and "wrong password" error messages and replace them both with a more generic error. This is to prevent people from bruteforcing usernames.
Edit: I've now also added a download button in the file info dialog which downloads a file as the original name. This makes it so that whoever owns the file can download it under it's original name from the UI.
=> Making the Frontpage use the SI Standard for file sizes, make Login error more ambiguous and download button

packages/backend/src/utils/Snippet.ts, packages/frontend/src/components/dialogs/FileInformationDialog.vue, packages/frontend/src/components/table/FilesTable.vue
- Fixed an issue were using a custom value to serve files from didn't apply to snippets
- Added a download link to download files with their original filenames on the table view
=> [Fix] Snippet download URL

packages/backend/package.json, packages/backend/src/utils/Thumbnails.ts, yarn.lock
A user on Discord was having an issue with images being black and white, and after further investigation this is happening to other people as well:
https://github.com/lovell/sharp/issues/3893
https://github.com/lovell/sharp/issues/3894
https://github.com/lovell/sharp/issues/3902
Since we're already using `ffmpeg` and `fluent-ffmpeg`, I decided to remove sharp and move that logic over to ffmpeg directly which seems to solve the issue.
=> [Fix] Remove sharp

packages/backend/src/prisma/migrations/20240115115628_add_description_to_albums_and_snippets/migration.sql, packages/backend/src/prisma/schema.prisma, packages/backend/src/routes/album/GetAlbum.schema.ts, packages/backend/src/routes/album/GetAlbum.ts, packages/backend/src/routes/album/GetAlbumWithIdentifier.schema.ts, packages/backend/src/routes/album/GetAlbumWithIdentifier.ts, packages/backend/src/routes/album/GetAlbums.schema.ts, packages/backend/src/routes/album/GetAlbums.ts, packages/backend/src/routes/album/UpdateAlbum.schema.ts, packages/backend/src/routes/album/UpdateAlbum.ts, packages/backend/src/routes/snippet/GetSnippet.schema.ts, packages/backend/src/routes/snippet/GetSnippet.ts, packages/frontend/src/components/dialogs/AlbumSettingsDialog.vue, packages/frontend/src/components/dialogs/FileInformationDialog.vue, packages/frontend/src/pages/a/[identifier].vue, packages/frontend/src/store/albums.ts, packages/frontend/src/types.ts
This PRs adds the ability to give descriptions to album.
1. Go to the dashboard
2. Click on albums
3. Click on album settings icon
4. Set description
Now whenever you share a link to the album the description will appear beneath the name of the album.
Closes #517
=> [Feature] Add album descriptions

packages/backend/package.json, yarn.lock
Fixes https://github.com/chibisafe/uploader/pull/11
- Released a new version of the chibisafe uploader module to support utf-8 encoding on the filename
=> [Feature] Update chibisafe-uploader to accept UTF-8 filenames

packages/frontend/src/pages/dashboard/admin/settings.vue, packages/frontend/src/types.ts
This PR aims to fix the a mismatch between the front and backend. The frontend assumes that the blocked extension setting has a value that is a string, but in reality it is an array. This results in some errors and renders the function to remove a blocked extension unusable, as shown in #563 .
I had to work around some type errors by casting the setting's value as string[], but this is clearly shown in the code and I have modified the type itself to at least reference the fact that setting.value could be an array of strings.
The final change involves adding an extension. The input tip shows that you shouldn't include "." in front of the extension that the admin wants to add to the blocklist, but there is no code to add that "." before adding it to the array which is required for the …
=> Fix blocked extension management

docker-compose.dev.yml, docker-compose.example.yml, docker/DockerfileServer, packages/backend/src/routes/GetSettings.ts, packages/backend/src/structures/settings.ts, packages/next/.env.development, packages/next/.env.production.example, packages/next/src/app/(home)/guides/(content)/running-manually/page.mdx, packages/next/src/app/(home)/guides/(content)/running-with-docker/page.mdx, packages/next/src/app/layout.tsx, packages/next/src/components/GlobalAdminNotice.tsx, packages/next/src/types.ts
- Removed `SERVE_UPLOADS_FROM` env variable
- Added a banner for admins that shows up if `Serve uploads from` setting is not set in the dashboard, with a link to fix it.
=> feat: improve onboarding by making settings simpler

Caddyfile
Basically what the title says. The guide recommends folks to use their own proxy in front of the one in use to unify the frontend and the api, hence we should also make sure that Caddy is set up to allow for that kind of a structure by default.
=> Update Caddyfile to trust local proxies

README.md, packages/backend/src/prisma/migrations/20240417232629_add_url_shortener/migration.sql, packages/backend/src/prisma/schema.prisma, packages/backend/src/routes/links/CreateLink.ts, packages/backend/src/routes/links/DeleteLink.ts, packages/backend/src/routes/links/GetLink.ts, packages/backend/src/routes/links/GetLinks.ts, packages/backend/src/structures/interfaces.ts, packages/backend/src/structures/settings.ts, packages/backend/src/utils/Link.ts, packages/next/src/actions/LinksActions.ts, packages/next/src/app/dashboard/links/page.tsx, packages/next/src/app/l/[identifier]/route.ts, packages/next/src/components/DashboardSidebar.tsx, packages/next/src/components/dialogs/CreateShortUrlDialog.tsx, packages/next/src/components/drawers/CreateShortUrlDrawer.tsx, packages/next/src/components/forms/SettingsForm.tsx, packages/next/src/components/tables/links-table/LinksConfirmationAction.tsx, packages/next/src/components/tables/links-table/LinksTable.tsx, packages/next/src/types.ts
=> feat: URL shortener

packages/backend/src/routes/health/HealthCheck.ts
Another short and sweet PR.
Add an endpoint for health checking. This can be used in conjunction with other apps to send notifications in case something goes wrong with the API server. We also have the option of adding other checks, such as db access, in the near future.
=> Add basic health check endpoint to API

packages/next/src/components/FileThumbnail.tsx, packages/next/src/components/Masonry.tsx, packages/next/src/components/dialogs/FileInformationDialog.tsx, packages/next/src/lib/atoms/fileInformationDialog.ts, packages/next/src/types.ts
- Enables switching previous/next file with arrow keys
- Enables pressing the new floating arrow icons to switch previous/next file
=> feat: enable carousel for masonry

packages/backend/src/utils/Util.ts
Closes #586 . Not sure if there are ways to improve this implementation, maybe some input sanitation in the future?
Tested on my machine and works.
PS: Do note that the env var has to be applied to the API server and not the front end.
=> Add option to specify admin account password using env var

packages/next/src/content/guides/running-with-nginx-proxy-manager.mdx
I added a running with nginx proxy manager without the internal docker caddy (so with docker) guide.
Feel free to review if I made any typos or anything, I tested it locally and it works fine and looks fine too.
=> Added running with nginx proxy manager guide

packages/next/src/content/guides/running-with-docker.mdx
Slight fixes and a bit more clarification on directory structures. Hopefully prevents confusion between Caddy within chibisafe vs Caddy on the host machine
=> Update running-with-docker.mdx to clarify directory structure

packages/next/src/content/guides/using-a-file-change-monitor.mdx
As discussed, this is a neat workaround for end users who use screenshot managers that don’t support third-party integrations. I will add more to it in the near future.
=> docs: add fswatch guide

packages/next/src/components/dialogs/bulk-actions/BulkAlbumActions.tsx
=> Fix typo in the 'Manage albums' modal

packages/next/src/hooks/useUploadFile.ts
Digital ocean spaces require "x-amz-acl" header to be present if you want file to be public. I made this simple yet ugly change in order to be able to use DigitalOcean.
I know it looks bad, however there is no point doing this as a setting since this problem seems to be unique to DigitalOcean.
=> x-amz-acl header for DigitalOcean Spaces

packages/backend/src/prisma/migrations/20250705131250_add_s3pathstyle_setting/migration.sql, packages/backend/src/prisma/schema.prisma, packages/backend/src/structures/interfaces.ts, packages/backend/src/structures/s3.ts, packages/backend/src/structures/settings.ts, packages/next/src/components/forms/SettingsForm.tsx
Added a simple toggle to the settings to enable path style buckets when using s3 for storage, allows usage of several S3 compatible storage solutions.
=> feat: path style bucket setting for s3
